# Generated by Django 3.1.5 on 2021-01-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterpreneurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discriptions', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('act', 'active'), ('inact', 'inactive')], max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Field_of_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourism.field_of_activity')),
            ],
        ),
        migrations.CreateModel(
            name='Toursites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('act', 'active'), ('inact', 'inactive')], max_length=50)),
                ('discription', models.TextField()),
                ('coordinates', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('field_of_activity', models.ManyToManyField(related_name='toursites', to='tourism.Field_of_activity')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=150)),
                ('enterpreneur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_enterpreneur', to='tourism.enterpreneurs')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_toursites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=100)),
                ('toursite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_toursite', to='tourism.toursites')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_enterpreneurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=100)),
                ('enterpreneur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_enterpreneur', to='tourism.enterpreneurs')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('enterpreneur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_enterpreneur', to='tourism.enterpreneurs')),
            ],
        ),
        migrations.AddField(
            model_name='enterpreneurs',
            name='toursite_id',
            field=models.ManyToManyField(related_name='enterpreneur_toursite', to='tourism.Toursites'),
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pub', 'publish'), ('not_pub', 'not published')], max_length=50)),
                ('enterpreneur_id', models.ManyToManyField(related_name='articles_enterpreneur', to='tourism.Enterpreneurs')),
                ('toursite_id', models.ManyToManyField(related_name='articles_toursite', to='tourism.Toursites')),
            ],
        ),
    ]
