# Generated by Django 3.1.5 on 2021-01-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
